### ISSUE TITLE
Update terminal copy

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/playerchain-demo#106]
### Start a chain flow
 - Add a message after initialise message saying "This game works best with 4 players"
 - Change discord message to: "Looking for a group? Join our Discord and paste your key in the #lfg channel: LINK"

### Join a chain
- Clear screen after the user selects "join game" and then start printing new text lines
- Change discord text to "Looking for a game? Check the #lfg channel in our discord for public games: LINK"

### Joining a chain
- Add a new line after the key message: "If you would like to start you own game, click here to go back" and add the go back functionality

**Comment by chrisfarms** [comment]
the "discord link" text should be updated as part of this task https://github.com/playmint/playerchain-demo/pull/176

**Comment by chrisfarms** [comment]
the "This invite link is for the wrong version" text probably wants some love too
