### ISSUE TITLE
Need to stop flying into out-of-play spaces

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/playerchain-demo#125]
- Middle circle
- Exterior walls

(Would be nice to solve all wall clip through but these are the higher priority ones)

Some options for these are:
- Massive colliders
- If a player is in one of these areas they are immediately killed

**Comment by ldunnplaymint** [comment]
Absolute minimum is remove the circle in the middle of the map.

Better fix would be to make the walls a bit fatter
