### ISSUE TITLE
Connection issues widget appears at the start and end of a session

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/playerchain-demo#151]
It should probably just be invisible until the countdown ends and then turned off when the leaderboard appears

**Comment by chrisfarms** [comment]
tricky as the connection thing is seperate from the "game" it doesn't know about the countdown

I recon it just needs to be more sensitive: require 0CPS for 10 seconds in a row or something like that

**Comment by ldunnplaymint** [comment]
Fix along side #155
