### ISSUE TITLE
The simulation takes too long to run or we fly through walls

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/playerchain-demo#157]
a single tick of the simulation takes upwards of 5ms for 4 players with 2 or more physics steps

we have dropped the physics steps to 1 ... and are happy with the performance here... but now we fly through falls as there are not enough physics steps.

we need to either reimplement the physics system to operating effciently/effectively in a single step, or make it fast enough that we can afford to run more steps.

**Comment by chrisfarms** [comment]
seems we are happy with the improvements from work in #160, #167, #190 

there's more opportunities to imporove simulation runs / physics, but I think we happy where we are for now unless something else comes up
