### ISSUE TITLE
Separate UI palette to ship palette

### ISSUE THREAD

**Issue by tboho1** [playmint/playerchain-demo#163]
Colors are currently optimized for the ship materials, but lack contrast when used for the text.

There should be two separate sets which we can control independently for each context. UI elements would use the same set as text.

**Comment by chrisfarms** [comment]
```
Blue   #0096ff
Red   #ff348f
Purple   #bf6cff
Yellow   #e49100
Teal   #00c0be
```

see [discord](https://discord.com/channels/1115267313718018048/1116391653259882516/1297888203772006521)
