### ISSUE TITLE
Blocklace trailing lines pierces the FPS counter UI element 

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/playerchain-demo#24]
Packet lace canvas does not resize with the window being resized

<img width="256" alt="Screenshot 2024-09-30 at 09 48 40" src="https://github.com/user-attachments/assets/c1e3a604-90b2-46ab-8d91-978a2cc802a2">

**Comment by chrisfarms** [comment]
blocklace lines have gone completely as there are no commits before start now .... closing this as it doesn't make sense now, but prob need a new issue for "fake some lines or put something else interesting in the sidebar"
