### ISSUE TITLE
Automate adding close window on windows

### ISSUE THREAD

**Issue by chrisfarms** [playmint/playerchain-demo#66]
on windows the webview titlebar does not have the close "x"

this is because socket.ini sets the window `titlebar_style` to 'hidden' ... which is correct for mac and linux, but doesn't act right on windows.

on windows we don't want that key set at all .... but there is no easy way to change that value just for windows without editing the ini file .... so we may need to do something horrible like template out the socket.ini for each platform before build

**Comment by hypnoshock** [comment]
☝️Horrible enough for you @chrisfarms? 😅
